# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: jeonghwan-kim.github.io
title: 김정환 블로그
description: 주로 웹 기술에 대해 이야기 합니다
url: https://jeonghwan-kim.github.io
profile_url: /assets/imgs/me.jpg
email: ej88ej@gmail.com
google_analytics_token: UA-31588166-2
twitter_username: jeonghwan0424
github_username:  jeonghwan-kim
facebook_username: jeonghwan0424
linkedin_username: jeonghwan-kim-07706488

# Handling Reading
exclude: ['node_modules', 'vendor'] # Remove comment at local evelopment mode

# markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 10

